# Generated by Django 5.0.7 on 2024-08-24 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user', models.CharField(max_length=64, verbose_name='username here')),
                ('post_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('post', models.TextField(verbose_name='Enter your post here')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('liking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_no', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Post_comments',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='network.post')),
                ('comment_id', models.IntegerField()),
                ('user', models.CharField(max_length=64, verbose_name='user')),
                ('comments', models.CharField(max_length=1024, verbose_name='Comments')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.CharField(max_length=2048)),
                ('following', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
