# Generated by Django 5.0.7 on 2024-08-25 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_liking_post_comments_liking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_comments',
            name='liking',
        ),
        migrations.AddField(
            model_name='post',
            name='liking',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
