# Generated by Django 5.0.7 on 2024-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_comments_liking_post_liking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liking',
        ),
        migrations.AddField(
            model_name='statistics_user',
            name='bio',
            field=models.TextField(blank='My bio is this', verbose_name='Your bio here'),
        ),
        migrations.AddField(
            model_name='statistics_user',
            name='liking',
            field=models.ManyToManyField(to='network.post'),
        ),
        migrations.AddField(
            model_name='statistics_user',
            name='user',
            field=models.CharField(default='user', max_length=64, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='comment_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
