# Generated by Django 5.0.7 on 2024-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_liking_statistics_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='comment_id',
            field=models.IntegerField(),
        ),
    ]
