# Generated by Django 5.0.7 on 2024-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_comments_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='comment_id',
            field=models.IntegerField(blank=True),
        ),
    ]
