# Generated by Django 5.0.7 on 2024-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_post_comments_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='comment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
