# Generated by Django 5.0.7 on 2024-08-26 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_comments_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics_user',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statistics_user',
            name='liking',
            field=models.ManyToManyField(blank=True, to='network.post'),
        ),
    ]
