# Generated by Django 5.0.7 on 2024-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_statistics_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics_user',
            name='bio',
            field=models.TextField(default='My bio is this', verbose_name='Your bio here'),
        ),
    ]
