# Generated by Django 5.0.7 on 2024-08-26 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_statistics_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liking',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
