# Generated by Django 5.0.7 on 2024-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_liking'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
