# Generated by Django 5.0.7 on 2024-08-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
